name: Demo Build and Publish

on:
  push:
    branches:
      - main
      - dev

env:
  WEBAPP_NAME: skynet-gh

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout local
        uses: actions/checkout@v2

      - name: Install DOTNET on runner
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Build app
        run: |
          dotnet restore
          dotnet build -c Release --no-restore
          dotnet test
          dotnet publish -c Release -o ./out

      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: published_app
          path: ./out

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: download artifacts
        uses: actions/download-artifact@v1
        with:
          name: published_app
          path: ./out

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to test app
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          package: "./out"
