name: Demo Build and Publish

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout local
        uses: actions/checkout@v2

      - run: |
          echo "This is working"
